/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "rgb(var(--c-primary) / <alpha-value>)",
        "primary-50": "rgb(var(--c-primary-50) / <alpha-value>)",
        "primary-100": "rgb(var(--c-primary-100) / <alpha-value>)",
        "primary-200": "rgb(var(--c-primary-200) / <alpha-value>)",
        "primary-300": "rgb(var(--c-primary-300) / <alpha-value>)",
        "primary-400": "rgb(var(--c-primary-400) / <alpha-value>)",
        "primary-500": "rgb(var(--c-primary-500) / <alpha-value>)",
        "primary-600": "rgb(var(--c-primary-600) / <alpha-value>)",
        "primary-700": "rgb(var(--c-primary-700) / <alpha-value>)",
        "primary-800": "rgb(var(--c-primary-800) / <alpha-value>)",
        "primary-900": "rgb(var(--c-primary-900) / <alpha-value>)",
        secondary: "rgb(var(--c-secondary) / <alpha-value>)",
        "secondary-50": "rgb(var(--c-secondary-50) / <alpha-value>)",
        "secondary-100": "rgb(var(--c-secondary-100) / <alpha-value>)",
        "secondary-200": "rgb(var(--c-secondary-200) / <alpha-value>)",
        "secondary-300": "rgb(var(--c-secondary-300) / <alpha-value>)",
        "secondary-400": "rgb(var(--c-secondary-400) / <alpha-value>)",
        "secondary-500": "rgb(var(--c-secondary-500) / <alpha-value>)",
        "secondary-600": "rgb(var(--c-secondary-600) / <alpha-value>)",
        "secondary-700": "rgb(var(--c-secondary-700) / <alpha-value>)",
        "secondary-800": "rgb(var(--c-secondary-800) / <alpha-value>)",
        "secondary-900": "rgb(var(--c-secondary-900) / <alpha-value>)",
        accent: "rgb(var(--c-accent) / <alpha-value>)",
        "accent-50": "rgb(var(--c-accent-50) / <alpha-value>)",
        "accent-100": "rgb(var(--c-accent-100) / <alpha-value>)",
        "accent-200": "rgb(var(--c-accent-200) / <alpha-value>)",
        "accent-300": "rgb(var(--c-accent-300) / <alpha-value>)",
        "accent-400": "rgb(var(--c-accent-400) / <alpha-value>)",
        "accent-500": "rgb(var(--c-accent-500) / <alpha-value>)",
        "accent-600": "rgb(var(--c-accent-600) / <alpha-value>)",
        "accent-700": "rgb(var(--c-accent-700) / <alpha-value>)",
        "accent-800": "rgb(var(--c-accent-800) / <alpha-value>)",
        "accent-900": "rgb(var(--c-accent-900) / <alpha-value>)",
        bg: "rgb(var(--c-bg) / <alpha-value>)",
        ink: "rgb(var(--c-text) / <alpha-value>)",
      },
      fontFamily: {
        heading: ["var(--f-heading)", "system-ui", "sans-serif"],
        body: ["var(--f-body)", "system-ui", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "var(--radius)",
        sm: "4px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        "2xl": "32px",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        sm: "0 1px 3px 0 rgb(0 0 0 / 0.08), 0 1px 2px -1px rgb(0 0 0 / 0.06)",
        DEFAULT: "0 2px 6px -1px rgb(0 0 0 / 0.08), 0 2px 4px -2px rgb(0 0 0 / 0.05)",
        md: "0 4px 10px -2px rgb(0 0 0 / 0.08), 0 2px 6px -2px rgb(0 0 0 / 0.05)",
        lg: "0 10px 20px -4px rgb(0 0 0 / 0.10), 0 4px 8px -4px rgb(0 0 0 / 0.05)",
        xl: "0 18px 32px -8px rgb(0 0 0 / 0.12), 0 6px 12px -6px rgb(0 0 0 / 0.06)",
        "2xl": "0 28px 50px -12px rgb(0 0 0 / 0.18)",
      },
    },
  },
  plugins: [],
};
